CREATE TABLE stories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  synopsis TEXT NOT NULL,
  category VARCHAR(255) NOT NULL,
  storyCover VARCHAR(255) NOT NULL,
  categoryId INT NOT NULL,
  status VARCHAR(255) NOT NULL
  FOREIGN KEY (categoryId) REFERENCES stories(id)
);

CREATE TABLE chapters (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  storyChapter TEXT NOT NULL,
  storyId INT NOT NULL,
  FOREIGN KEY (storyId) REFERENCES stories(id)
);
CREATE TABLE tags (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  storyId INT,
  FOREIGN KEY (storyId) REFERENCES stories(id)
);
CREATE TABLE category (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,

);

